# Generated by Django 4.1.5 on 2023-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moderador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('Descricao', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='media/foto')),
            ],
        ),
        migrations.CreateModel(
            name='prelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('Descricao', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='media/foto')),
            ],
        ),
    ]
