# Generated by Django 4.1.5 on 2023-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('prelector', models.CharField(max_length=200)),
                ('Tempo', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=200)),
                ('Descricao', models.CharField(max_length=200)),
                ('Titulo_break', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50)),
                ('Ppt', models.FileField(upload_to='', verbose_name='media/ptt')),
            ],
        ),
        migrations.CreateModel(
            name='Programa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('prelector', models.CharField(max_length=200)),
                ('Tempo', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=200)),
                ('Descricao', models.CharField(max_length=200)),
                ('Titulo_break', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50)),
                ('Ppt', models.FileField(upload_to='', verbose_name='media/ptt')),
            ],
        ),
    ]
