# Generated by Django 4.1.5 on 2023-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_programa1_programa2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa1',
            name='Descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa1',
            name='Ppt',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='media/ptt'),
        ),
        migrations.AlterField(
            model_name='programa1',
            name='Tempo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa1',
            name='Titulo_break',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='programa1',
            name='horario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa1',
            name='prelector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='Descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='Ppt',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='media/ptt'),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='Tempo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='Titulo_break',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='horario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='prelector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
