# Generated by Django 4.1.5 on 2023-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0004_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderador',
            name='data',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
