# Generated by Django 4.1.5 on 2023-05-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0005_moderador_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='Ppt',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='moderador',
            name='data',
        ),
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
