# Generated by Django 4.1.5 on 2023-05-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0008_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTICIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('fotos', models.FileField(blank=True, null=True, upload_to='', verbose_name='media/noticia')),
                ('data', models.DateField()),
            ],
        ),
    ]
