# Generated by Django 4.1.5 on 2023-05-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0009_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fotos',
            field=models.FileField(blank=True, null=True, upload_to='media/noticia'),
        ),
        migrations.AlterField(
            model_name='programa1',
            name='Ppt',
            field=models.FileField(blank=True, null=True, upload_to='media/ptt'),
        ),
        migrations.AlterField(
            model_name='programa2',
            name='Ppt',
            field=models.FileField(blank=True, null=True, upload_to='media/ptt'),
        ),
    ]
