# Generated by Django 4.2.4 on 2023-08-29 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0011_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
