# Generated by Django 4.2.4 on 2023-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0012_inscricao_data_created_inscricao_data_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
