# Generated by Django 4.2.4 on 2023-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0015_inscricao_convidados_inscricao_evento_inscricao_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='Convidados',
            field=models.CharField(choices=[('Delegado', 'Delegado'), ('Visitante', 'Visitante'), ('Imprensa', 'Imprensa')], default='Conferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Evento',
            field=models.CharField(choices=[('Conferência', 'Conferencia'), ('Whorkshop', 'Whorkshop'), ('Exposição', 'Exposição')], default='Conferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='urt',
            field=models.CharField(max_length=100),
        ),
    ]
