# Generated by Django 4.2.4 on 2023-09-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0016_alter_inscricao_convidados_alter_inscricao_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='image',
            field=models.ImageField(blank=True, default='Vazio', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='urt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Website'),
        ),
    ]
