# Generated by Django 4.2.4 on 2023-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0017_alter_inscricao_image_alter_inscricao_urt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='exposicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='titulo',
            field=models.CharField(choices=[('Sr', 'Sr'), ('Sra', 'Sra')], default='Sr.', max_length=10),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='workshop',
            field=models.BooleanField(default=False),
        ),
    ]
