# Generated by Django 4.2.4 on 2023-10-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0018_inscricao_exposicao_inscricao_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='exposicao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='workshop',
        ),
    ]
