# Generated by Django 4.2.4 on 2023-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0019_remove_inscricao_exposicao_remove_inscricao_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='exposicao',
            field=models.BooleanField(default=False, verbose_name='Exposicao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='sr',
            field=models.BooleanField(default=False, verbose_name='Sr'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='sra',
            field=models.BooleanField(default=False, verbose_name='Sra'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='workshop',
            field=models.BooleanField(default=False, verbose_name='Workshop'),
        ),
    ]
