# Generated by Django 4.2.4 on 2023-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0020_inscricao_exposicao_inscricao_sr_inscricao_sra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='genero',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Rejeitado', 'Rejeitado'), ('Aceite', 'Aceite')], default='Aguardando', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Evento',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Conferencia', max_length=20),
        ),
    ]
