# Generated by Django 4.2.4 on 2023-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0021_inscricao_genero_alter_inscricao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Aguardando', max_length=20, verbose_name='Genero'),
        ),
    ]
