# Generated by Django 4.2.4 on 2023-10-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0022_alter_inscricao_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='sr',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='sra',
        ),
    ]
