# Generated by Django 4.2.4 on 2023-10-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landpage', '0024_remove_inscricao_exposicao_remove_inscricao_workshop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='Convidados',
            field=models.CharField(choices=[('Delegado', 'Delegado'), ('Visita ', 'Visita a área de Exposição')], default='Delegado', max_length=20),
        ),
        migrations.CreateModel(
            name='encontrosb2b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('Pais', models.CharField(max_length=100, verbose_name='País de Origem ')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Rejeitado', 'Rejeitado'), ('Aceite', 'Aceite')], default='Aguardando', max_length=20)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='Vazio', null=True, upload_to='images')),
                ('user_updadte', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('Pais', models.CharField(max_length=100, verbose_name='País de Origem ')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Rejeitado', 'Rejeitado'), ('Aceite', 'Aceite')], default='Aguardando', max_length=20)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='Vazio', null=True, upload_to='images')),
                ('Pacotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.pacotes')),
                ('user_updadte', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
