# Generated by Django 4.2.4 on 2023-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0026_pacotes_valor_alter_inscricao_convidados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotes',
            name='valor',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
