# Generated by Django 4.2.4 on 2023-10-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0028_alter_pacotes_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
