# Generated by Django 4.2.4 on 2023-10-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0032_alter_pacotespatrocinio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotespatrocinio',
            name='valor',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
