# Generated by Django 4.2.4 on 2023-10-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0033_alter_pacotespatrocinio_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacotespatrocinio',
            old_name='valor',
            new_name='Cedula',
        ),
    ]
