# Generated by Django 4.2.4 on 2023-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0034_rename_valor_pacotespatrocinio_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotespatrocinio',
            name='Cedulas',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
