# Generated by Django 4.2.4 on 2023-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0036_remove_pacotespatrocinio_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacotespatrocinio',
            name='Cedulas',
        ),
        migrations.AddField(
            model_name='pacotespatrocinio',
            name='valor',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
