# Generated by Django 4.2.4 on 2023-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0041_pacotes_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresapatrocinio',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='encontrosb2b',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao_empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
